"""soft delete and fix primary key

Revision ID: 5cea9d422f02
Revises: 918fa8da2f09
Create Date: 2025-09-13 11:04:05.023370

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cea9d422f02'
down_revision: str | Sequence[str] | None = '918fa8da2f09'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'user_id')
    # ### end Alembic commands ###
