"""add deleted_at field

Revision ID: 918fa8da2f09
Revises: 28ce9fcdc183
Create Date: 2025-09-12 02:03:32.759683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918fa8da2f09'
down_revision: Union[str, Sequence[str], None] = '28ce9fcdc183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'deleted_at')
    # ### end Alembic commands ###
