# runs on main and pull requests into main
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# runs jobs on ubuntu-latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
          poetry env activate
        working-directory: ./bot
      - name: Run tests
        run: |
          poetry run pytest
        working-directory: ./bot
      - name: build package
        run: |
          poetry build
        working-directory: ./bot
      - name: create docker image
        run: |
          docker build -t expanses-tracker-tbot:local .
        working-directory: ./bot
      - name: save docker image as tar
        run: |
          docker save expanses-tracker-tbot:local -o expanses-tracker-tbot.tar
      - name: Upload docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: expanses-tracker-tbot-image
          path: expanses-tracker-tbot.tar
          compression-level: 9

